// Internal endpoints called by the Cloudflare chat-ws Worker.
// Two routes, both gated by a shared HMAC header (Resource.ChatWsHmacSecret).
//
//   POST /internal/chat/verify-session
//     body: { token }
//     200:  { userId }
//     401:  unauthenticated bearer
//
//   POST /internal/chat/persist
//     body: { chatId, messages: [{ clientMsgId, senderId, ciphertext, nonce }] }
//     200:  { rows: [{ clientMsgId, serverMsgId, ts }], pushTargets: [userId] }
//     401:  bad HMAC
//     409:  sender not a member of chatId
//
// ciphertext + nonce are base64-encoded over the wire (JSON has no native
// bytes type) and decoded back to Bytes columns on insert.

import { Resource } from "sst";

import { prisma } from "@repo/database";

import { auth } from "./auth";

// Resource augmentation — sst-env.d.ts is regenerated by `sst dev`/`sst deploy`
// and will include ChatWsHmacSecret once the chat-ws stack is first deployed.
// Declared here so typecheck passes ahead of the first SST run.
declare module "sst" {
  interface Resource {
    ChatWsHmacSecret: {
      type: "sst.sst.Secret";
      value: string;
    };
  }
}

const SECRET_HEADER = "x-chat-ws-secret";

interface PersistRequest {
  chatId: string;
  messages: Array<{
    clientMsgId: string;
    senderId: string;
    ciphertext: string;
    nonce: string;
  }>;
}

interface PersistResponse {
  rows: Array<{ clientMsgId: string; serverMsgId: string; ts: number }>;
  pushTargets: string[];
}

interface VerifySessionRequest {
  token: string;
}

interface VerifySessionResponse {
  userId: string;
}

function verifyHmac(request: Request): boolean {
  const got = request.headers.get(SECRET_HEADER);
  if (!got) return false;
  const expected = Resource.ChatWsHmacSecret.value;
  // Constant-time compare — short strings, but still avoid early exit.
  if (got.length !== expected.length) return false;
  let acc = 0;
  for (let i = 0; i < got.length; i++) {
    acc |= got.charCodeAt(i) ^ expected.charCodeAt(i);
  }
  return acc === 0;
}

export async function handleChatInternal(
  request: Request,
  path: string,
): Promise<Response | null> {
  if (!path.startsWith("/internal/chat/")) return null;
  if (request.method !== "POST") {
    return new Response("method not allowed", { status: 405 });
  }
  if (!verifyHmac(request)) {
    return new Response("unauthorized", { status: 401 });
  }

  const sub = path.slice("/internal/chat/".length);
  switch (sub) {
    case "verify-session":
      return handleVerifySession(request);
    case "persist":
      return handlePersist(request);
    default:
      return new Response("not found", { status: 404 });
  }
}

async function handleVerifySession(request: Request): Promise<Response> {
  let body: VerifySessionRequest;
  try {
    body = (await request.json()) as VerifySessionRequest;
  } catch {
    return new Response("bad json", { status: 400 });
  }
  if (!body?.token) return new Response("missing token", { status: 400 });

  // Better Auth's bearer plugin reads from Authorization header.
  const headers = new Headers();
  headers.set("Authorization", `Bearer ${body.token}`);
  const session = await auth.api.getSession({ headers });
  if (!session?.user?.id) {
    return new Response("invalid session", { status: 401 });
  }

  const out: VerifySessionResponse = { userId: session.user.id };
  return new Response(JSON.stringify(out), {
    status: 200,
    headers: { "content-type": "application/json" },
  });
}

async function handlePersist(request: Request): Promise<Response> {
  let body: PersistRequest;
  try {
    body = (await request.json()) as PersistRequest;
  } catch {
    return new Response("bad json", { status: 400 });
  }
  if (
    !body?.chatId ||
    !Array.isArray(body.messages) ||
    body.messages.length === 0
  ) {
    return new Response("bad request", { status: 400 });
  }

  // Membership check — every senderId in the batch must belong to chatId.
  // Cheaper than per-row: fetch the member set once.
  const members = await prisma.chatMember.findMany({
    where: { chatId: body.chatId },
    select: { userId: true },
  });
  const memberIds = new Set(members.map((m) => m.userId));
  for (const m of body.messages) {
    if (!memberIds.has(m.senderId)) {
      return new Response(
        JSON.stringify({ error: "not a member", senderId: m.senderId }),
        { status: 409, headers: { "content-type": "application/json" } },
      );
    }
  }

  // Insert all rows in one transaction. createMany is faster but Prisma
  // does not return inserted IDs from createMany on Postgres; we need them
  // for the ack frame, so fall back to per-row create inside a transaction
  // for now. Optimisation later: raw SQL with RETURNING.
  const inserted = await prisma.$transaction(
    body.messages.map((m) =>
      prisma.chatMessage.create({
        data: {
          chatId: body.chatId,
          senderId: m.senderId,
          clientMsgId: m.clientMsgId,
          ciphertext: Buffer.from(m.ciphertext, "base64"),
          nonce: Buffer.from(m.nonce, "base64"),
        },
        select: { id: true, clientMsgId: true, createdAt: true },
      }),
    ),
  );

  const rows = inserted.map((row) => ({
    clientMsgId: row.clientMsgId,
    serverMsgId: row.id,
    ts: row.createdAt.getTime(),
  }));

  // pushTargets: stub for now. Real impl checks recent device-presence (via
  // Worker → API heartbeat or Better Auth session.lastSeen) and returns
  // userIds we should fan to APNs/FCM. M6 owns the actual push pipeline.
  const out: PersistResponse = { rows, pushTargets: [] };
  return new Response(JSON.stringify(out), {
    status: 200,
    headers: { "content-type": "application/json" },
  });
}
